import type { ProviderConfig } from '../types';

// 다중 LLM 폴백 체인. 무료부터 소진 → 유료(isPaid)는 enabled 체크된 것만 사용.
// 키는 사용자가 환경설정에서 입력. baseUrl='' 이면 네이티브 Gemini, 있으면 OpenAI 호환.
export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  { id: 'gemini-free',   label: 'Gemini (무료)',        apiKey: '', baseUrl: '', model: 'gemini-flash-lite-latest', kind: 'gemini', isPaid: false, enabled: true },
  { id: 'openrouter-a',  label: 'OpenRouter 무료 A',     apiKey: '', baseUrl: 'https://openrouter.ai/api/v1', model: 'meta-llama/llama-3.3-70b-instruct:free', kind: 'openai', isPaid: false, enabled: true },
  { id: 'openrouter-b',  label: 'OpenRouter 무료 B',     apiKey: '', baseUrl: 'https://openrouter.ai/api/v1', model: 'google/gemini-2.0-flash-exp:free', kind: 'openai', isPaid: false, enabled: true },
  { id: 'groq-free',     label: 'Groq (무료)',          apiKey: '', baseUrl: 'https://api.groq.com/openai/v1', model: 'llama-3.3-70b-versatile', kind: 'openai', isPaid: false, enabled: true },
  { id: 'gemini-paid',   label: 'Gemini (유료)',        apiKey: '', baseUrl: '', model: 'gemini-flash-latest', kind: 'gemini', isPaid: true, enabled: false },
  { id: 'claude-paid',   label: 'Claude API (유료)',    apiKey: '', baseUrl: 'https://api.anthropic.com/v1', model: 'claude-3-5-haiku-latest', kind: 'openai', isPaid: true, enabled: false },
];


export const GENRE_PRESETS = [
  {
    id: 'lofi',
    nameKo: 'Lo-fi',
    nameEn: 'Lo-fi',
    iconName: 'Moon',
    bgColor: '#7C3AED', // Deep Violet/Purple
    defaultMood: '몽환적인, 차분한 새벽 감성',
    defaultScene: '비 오는 새벽 서울 골목길과 창문',
    defaultKeywords: 'lofi hip hop, chill beats, cozy rain, study music, late night insomnia',
    defaultVocal: '연주곡 (보컬 없음)',
  },
  {
    id: 'pop',
    nameKo: 'Pop',
    nameEn: 'Pop',
    iconName: 'PartyPopper',
    bgColor: '#E11D48', // Vibrant Rose Pink
    defaultMood: '설레고 경쾌하며 트렌디한',
    defaultScene: '화창한 주말 한강 피크닉 또는 드라이브',
    defaultKeywords: 'catchy pop, synth pop, upbeat groove, bright summer, driving playlist',
    defaultVocal: '여성 보컬 (맑고 청량함)',
  },
  {
    id: 'jazz',
    nameKo: 'Jazz',
    nameEn: 'Jazz',
    iconName: 'GlassWater',
    bgColor: '#D97706', // Warm Amber
    defaultMood: '낭만적이고 그윽하며 고급스러운',
    defaultScene: '비 내리는 저녁 촛불 켜진 LP 바',
    defaultKeywords: 'smooth jazz, cozy cafe, piano trio, saxophone, midnight cocktail',
    defaultVocal: '연주곡 (보컬 없음)',
  },
  {
    id: 'rnb',
    nameKo: 'R&B',
    nameEn: 'R&B',
    iconName: 'Wine',
    bgColor: '#2563EB', // Electric Royal Blue
    defaultMood: '그루비하고 감각적이며 센티멘탈한',
    defaultScene: '네온사인이 비치는 도시의 심야 드라이브',
    defaultKeywords: 'smooth R&B, soul groove, mellow vocals, late night ride, modern urban',
    defaultVocal: '남녀 듀엣 보컬',
  },
  {
    id: 'indie',
    nameKo: 'Indie',
    nameEn: 'Indie',
    iconName: 'Trees',
    bgColor: '#059669', // Forest Emerald Green
    defaultMood: '풋풋하고 아련하며 서정적인',
    defaultScene: '가을바람 부는 숲길과 아늑한 통나무집',
    defaultKeywords: 'k-indie, acoustic guitar, warm nostalgia, youthful memories, gentle breeze',
    defaultVocal: '어쿠스틱 남성 보컬',
  },
  {
    id: 'study',
    nameKo: 'Study / Focus',
    nameEn: 'Study / Focus',
    iconName: 'BookOpen',
    bgColor: '#334155', // Slate Dark Blue
    defaultMood: '깊은 몰입과 정돈된 집중감',
    defaultScene: '조용한 도서관 창가 자리',
    defaultKeywords: 'deep focus, ambient study, alpha waves, binaural, productivity, minimal piano',
    defaultVocal: '연주곡 (보컬 없음)',
  },
  {
    id: 'workout',
    nameKo: 'Workout',
    nameEn: 'Workout',
    iconName: 'Dumbbell',
    bgColor: '#DC2626', // Crimson Red
    defaultMood: '폭발적인 에너지와 동기부여',
    defaultScene: '열기 가득한 피트니스 짐 & 러닝 트랙',
    defaultKeywords: 'intense workout, bass boost, phonk drive, high energy, gym motivation, 135bpm',
    defaultVocal: '에너제틱 랩/보컬',
  },
  {
    id: 'meditation',
    nameKo: 'Meditation',
    nameEn: 'Meditation',
    iconName: 'Sparkles',
    bgColor: '#0284C7', // Calming Sky Cyan
    defaultMood: '평온하고 치유되는 마음챙김',
    defaultScene: '새소리 들리는 아침 숲과 잔잔한 호숫가',
    defaultKeywords: 'mindfulness, sound healing, 432Hz ambient, deep sleep, zen meditation, water sounds',
    defaultVocal: '연주곡 (보컬 없음)',
  },
  {
    id: 'citypop',
    nameKo: 'City Pop',
    nameEn: 'City Pop',
    iconName: 'SunMedium',
    bgColor: '#9333EA', // Neon Violet
    defaultMood: '레트로하고 청량한 80년대 도회적 감성',
    defaultScene: '노을 지는 해변 고속도로와 도쿄 타워',
    defaultKeywords: '80s city pop, retro funk, brass section, sunset drive, nostalgic summer',
    defaultVocal: '여성 보컬 (레트로 팝)',
  },
  {
    id: 'acoustic',
    nameKo: 'Acoustic / Cafe',
    nameEn: 'Acoustic / Cafe',
    iconName: 'Coffee',
    bgColor: '#B45309', // Warm Coffee Brown
    defaultMood: '따스하고 편안한 오후의 여유',
    defaultScene: '햇살 들어오는 골목길 작은 베이커리 카페',
    defaultKeywords: 'acoustic cafe, warm guitar, soft afternoon, peaceful sunday, soothing vocals',
    defaultVocal: '감미로운 보컬',
  },
  {
    id: 'cinematic',
    nameKo: 'Cinematic / Epic',
    nameEn: 'Cinematic / Epic',
    iconName: 'Film',
    bgColor: '#4338CA', // Indigo Epic
    defaultMood: '웅장하고 벅차오르는 서사적 감동',
    defaultScene: '광활한 밤하늘과 별이 쏟아지는 산 정상',
    defaultKeywords: 'cinematic orchestra, epic emotional build, hans zimmer style, trailer music, inspiring',
    defaultVocal: '연주곡 (보컬 없음)',
  },
  {
    id: 'custom',
    nameKo: '직접 커스텀',
    nameEn: 'Custom Vibe',
    iconName: 'PlusCircle',
    bgColor: '#27272A', // Dark Zinc
    defaultMood: '사용자 맞춤형 특별한 분위기',
    defaultScene: '나만의 기억 속 특별한 공간',
    defaultKeywords: 'custom playlist, unique vibe, personalized music',
    defaultVocal: '연주곡 (보컬 없음)',
  },
];

export const I18N = {
  ko: {
    appTitle: 'AI Playlist Creator',
    headerSettings: '설정',
    headerHelp: '도움말',
    autoGenAll: '전체 7단계 원클릭 자동 생성',
    autoGenLoading: 'AI 자동 제작 진행 중...',
    genreTitle: '장르를 선택하세요',
    genreSubtitle: '오늘 만들고 싶은 유튜브 플레이리스트의 분위기는 무엇인가요?',
    promoText: '이 앱을 활용해서 만든 유튜브를 확인하세요.',
    promoBtn: 'Plab List 바로가기',
    developerCredit: 'Developer: AIPUTER',
    youtubeBtn: 'YouTube 바로가기',
    steps: {
      1: '1. 컨셉 상세 설정',
      2: '2. 이모지 제목 & SEO',
      3: '3. 감정곡선 트랙리스트',
      4: '4. Suno 프롬프트 스튜디오',
      5: '5. 구조 선택형 가사',
      6: '6. 1280×720 썸네일 캔버스',
      7: '7. 유튜브 업로드킷 패키징',
    },
    backToGenre: '← 장르 다시 선택하기',
    next: '다음 단계로 이동',
    prev: '이전 단계',
    generate: 'AI 새로 생성하기',
    exportTxt: '전체 키트 (.txt)',
    exportJson: '프로젝트 저장 (.json)',
    importJson: '프로젝트 불러오기',
    copySuccess: '클립보드에 복사되었습니다.',
    monitorTitle: 'LITELLM PROXY MONITOR',
    tokens: 'TOKENS',
    requests: 'REQUESTS',
    estimatedCost: 'ESTIMATED COST',
    liveStream: 'LIVE STREAM',
    statusOperational: 'STATUS: OPERATIONAL',
  },
  en: {
    appTitle: 'AI Playlist Creator',
    headerSettings: 'Settings',
    headerHelp: 'Help & Guide',
    autoGenAll: '1-Click Auto-Generate All 7 Steps',
    autoGenLoading: 'AI Pipeline Generating...',
    genreTitle: 'Select a Genre',
    genreSubtitle: 'What vibe of YouTube playlist do you want to create today?',
    promoText: 'Check out the YouTube channel made with this app.',
    promoBtn: 'Visit Plab List',
    developerCredit: 'Developer: AIPUTER',
    youtubeBtn: 'Visit YouTube Channel',
    steps: {
      1: '1. Concept Setup',
      2: '2. Emoji Titles & SEO',
      3: '3. Tracklist & Arc',
      4: '4. Suno Prompt Studio',
      5: '5. Structured Lyrics',
      6: '6. 1280×720 Thumbnail',
      7: '7. YouTube Upload Kit',
    },
    backToGenre: '← Back to Genre Selection',
    next: 'Next Step',
    prev: 'Previous Step',
    generate: 'Generate with AI',
    exportTxt: 'Export Kit (.txt)',
    exportJson: 'Save Project (.json)',
    importJson: 'Import Project',
    copySuccess: 'Copied to clipboard.',
    monitorTitle: 'LITELLM PROXY MONITOR',
    tokens: 'TOKENS',
    requests: 'REQUESTS',
    estimatedCost: 'ESTIMATED COST',
    liveStream: 'LIVE STREAM',
    statusOperational: 'STATUS: OPERATIONAL',
  },
};
